version: "3.3"

services:
    app:
      container_name: app
      restart: always
      build: .
      volumes:
        - .:/usr/src/app
      ports:
        - "8087:8080"
      links:
        - mongo
      depends_on:
        - mongo
      env_file:
        - ./.env
    mongo:
      container_name: mongo
      build:
        context: ./
        dockerfile: Dockerfile.mongo-seed
      ports:
        - 27017:27017
      #restart: always === removed for dev purpose
      environment:
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      #volumes:
      #  - ./data:/data/db